package integration;

import org.junit.Test;
import utils.TestUtils;

import java.io.File;
import java.util.List;

/**
 * This is an integration test.
 *
 * <p>The class {@link Lexer} is generated by JFLex from {@code src/main/jflex/ycalc.flex}.
 */
public class LexerTest {


    @Test
    public void testOutput() throws Exception {
        // given
        String inputFile = "src/test/resources/test.txt";
        String outputFile = "target/output.actual";
        String expectedFile = "src/test/resources/output.good";

        // when
        List<File> fileList = TestUtils.prepareFullIntegrationTest(inputFile, outputFile, expectedFile);

        // then
        TestUtils.checkFileContent(fileList);
    }


}
